version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    image: 'backend:0.1'
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
    - ./app:/app
    env_file:
      - .env.local
    build:
      context: ./
      dockerfile: ./Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    depends_on:
      - db
    env_file:
      - .env.local

volumes:
  app-db-data:
