version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - app/.env.local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    image: 'backend:0.1'
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./app:/app
    env_file:
      - app/.env
    build:
      context: ./app
      dockerfile: ./Dockerfile

volumes:
  db-data:
