namespace: default

env:
  HTTP_ADDR: ':5000'

image:
  name: bernatixer/stylizer
  pull: IfNotPresent

deployment:
  force: false
  replicas: 1
  container:
    name: stylizer
    port: 80

service:
  type: NodePort
  port: 80
  nodePort: 32323
