namespace: default

env:
  HTTP_ADDR: ':5000'

deployments:
  - name: core-service
    force: false
    replicas: 1
    nodePort: 31111
    container:
      name: stylizer
      image: bernatixer/stylizer
      port: 80

  - name: inference-service
    force: false
    replicas: 1
    nodePort: 32222
    container:
      name: inference
      image: bernatixer/inference-service
      port: 80
