namespace: default

deployments:
  - name: core-service
    replicas: 1
    port: 31111
    container:
      image: bernatixer/stylizer
      port: 80

  - name: inference-service
    replicas: 1
    port: 32222
    container:
      image: bernatixer/inference-service
      port: 80

persistances:
  - name: core-service-db
    storage: 10Gi
    port: 5432
