namespace: default

env:
  HTTP_ADDR: ':5000'

image:
  pull: IfNotPresent

deployment:
  force: false
  replicas: 2
  container:
    name: stylizer
    image: bernatixer/stylizer
    port: 80

service:
  type: NodePort
  port: 80
  nodePort: 32323
