name: Build & Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/stylizer:${{ steps.tag_version.outputs.new_tag }}

      # - name: Generate GitHub release tag
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}

      - uses: actions/checkout@v2
      - run: |
        ls -la

      - name: Update infra version
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: main
          targetBranch: main
          valueFile: 'infra/prod.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.tag_version.outputs.new_tag }}
          commitChange: true
          updateFile: true

      # - uses: actions/checkout@v2
      # - name: Git Commit
      #   run: |
      #     git config --global user.name "Continuous Integration"
      #     git config --global user.email "bernat.torres.bellido@gmail.com"
      #     git commit --allow-empty -m "📦 Release ${{ steps.tag_version.outputs.new_tag }} published 🚀"
      #     git push
