name: Deploy changes

on:
  push:
    branches:
      - main

jobs:
  notify_start:
    name: Notify start on slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Stylizer APP
          SLACK_ICON_EMOJI: ':frame_with_picture:'
          SLACK_COLOR: info
          SLACK_TITLE: 'Starting deployment for stylizer :package:'
          MSG_MINIMAL: true
          SLACK_FOOTER: ''

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@37.187.122.100:22/stylizer'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  notify_result:
    name: Notify result on slack
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Stylizer APP
          SLACK_ICON: https://img.icons8.com/color/452/van-gogh.png
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Deploy stylizer :rocket:'
          MSG_MINIMAL: 'actions url,commit'
          SLACK_FOOTER: 'Deployment finished with ${{ job.status }}'
