{{- $chartName := .Chart.Name }}
{{- $chartAppVersion := .Chart.AppVersion }}
{{- $nameSpace := .Values.namespace }}
{{- range $index, $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .chartName }}
  namespace: {{ .nameSpace }}
  labels:
    app: {{ .chartName }}
 
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .chartName }}
  template:
    metadata:
      labels:
        app: {{ .chartName }}
      {{- if $deployment.force }}
      annotations:
        roller: {{ randAlphaNum 5 }}
      {{- end }}
    spec:
      containers:
        - name: {{ $deployment.container.name }}
          image: "{{ $deployment.container.image }}:{{ .chartAppVersion }}"
          imagePullPolicy: {{ $deployment.container.pull }}
          ports:
            - containerPort: {{ $deployment.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .chartName }}
      imagePullSecrets:
        - name: dockerreg
{{- end }}