{{- $chartAppVersion := .Chart.AppVersion }}
{{- $nameSpace := .Values.namespace }}
{{- range $index, $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  namespace: {{ $nameSpace }}
  labels:
    app: {{ $deployment.name }}

spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
  template:
    metadata:
      labels:
        app: {{ $deployment.name }}
    spec:
      containers:
        - name: {{ $deployment.name }}
          image: "{{ $deployment.container.image }}:{{ $chartAppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $deployment.container.port }}
      imagePullSecrets:
        - name: dockerreg
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  namespace: {{ $nameSpace }}

spec:
  type: NodePort
  selector:
    app: {{ $deployment.name }}
  ports:
    - port: {{ $deployment.container.port }}
      targetPort: {{ $deployment.container.port }}
      nodePort: {{ $deployment.port }}
---
{{- end }}