{{- range $index, $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
 
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      {{- if $deployment.force }}
      annotations:
        roller: {{ randAlphaNum 5 }}
      {{- end }}
    spec:
      containers:
        - name: {{ $deployment.container.name }}
          image: "{{ $deployment.container.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pull }}
          ports:
            - containerPort: {{ $deployment.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
      imagePullSecrets:
        - name: dockerreg
---
{{- end }}