apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
 
spec:
  type: {{ .Values.service.type }}
  selector:
    role: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.port }}
      nodePort: {{ .Values.deployment.container.nodePort }}
